{% set version = "2.0.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-magrittr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/magrittr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/magrittr/magrittr_{{ version }}.tar.gz
  sha256: 6aba790c40de70d8fb4d2db4bebb377418971761b0da7df2141b5d4ad95981f3

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('magrittr')"           # [not win]
    - "\"%R%\" -e \"library('magrittr')\""  # [win]

about:
  home: https://magrittr.tidyverse.org, https://github.com/tidyverse/magrittr
  license: MIT
  summary: Provides a mechanism for chaining commands with a new forward-pipe operator, %>%. This operator will forward a value, or the result of an expression, into the next function call/expression. There is flexible support for the type of right-hand side expressions. For more information, see package vignette. To quote
    Rene Magritte, "Ceci n'est pas un pipe."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Type: Package
# Package: magrittr
# Title: A Forward-Pipe Operator for R
# Version: 2.0.1
# Authors@R: c(person(given = "Stefan Milton", family = "Bache", role = c("aut", "cph"), email = "stefan@stefanbache.dk", comment = "Original author and creator of magrittr"), person(given = "Hadley", family = "Wickham", role = "aut", email = "hadley@rstudio.com"), person(given = "Lionel", family = "Henry", role = "cre", email = "lionel@rstudio.com"), person(given = "RStudio", role = c("cph", "fnd")))
# Description: Provides a mechanism for chaining commands with a new forward-pipe operator, %>%. This operator will forward a value, or the result of an expression, into the next function call/expression. There is flexible support for the type of right-hand side expressions. For more information, see package vignette.  To quote Rene Magritte, "Ceci n'est pas un pipe."
# License: MIT + file LICENSE
# URL: https://magrittr.tidyverse.org, https://github.com/tidyverse/magrittr
# BugReports: https://github.com/tidyverse/magrittr/issues
# Suggests: covr, knitr, rlang, rmarkdown, testthat
# VignetteBuilder: knitr
# ByteCompile: Yes
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# NeedsCompilation: yes
# Packaged: 2020-11-17 12:44:34 UTC; lionel
# Author: Stefan Milton Bache [aut, cph] (Original author and creator of magrittr), Hadley Wickham [aut], Lionel Henry [cre], RStudio [cph, fnd]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-11-17 16:20:06 UTC
