# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R-BASE=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Wcn5xXt/LnrKcaGIYHwK+K1AvBpUKNDxcIqEriswxk7ek90wae8PdshakKAK+FX4MidXK4CjYW1vYd3jpA5Pw53HMcKEF2ASJqlV1L5+cT05OprC0rI9G0sehKFG5uIhrRACknu8fpUSaR1GbakjJ2FZf4Pc7LiTYu9CSFWm2qFPab969U9wOshhyYiGG4tp144Ti2VhqgYar9j3c7AO75VnZ2kY5KjG2HdVuxyvZXljXcILVpfNacC9rGoK+NNSJkG6jThS8B3C09SQGmXmCVCOe7IDt502mmVhF/er3l6upvgu+YeoWstSAqf/Ko6g/OTk7UwryQrH1oDiGzZpi5f9mihbgqgbht5zbApd9NTsg2b70idwdhlw61J1xnCzJ9ozYYhOupismwfhJIvFFPDT3rwGc7ZjPq7t/C2BFOyjquGIUDH1+RBhpGxR4FbFSYgDwlvrv4zRaP0X0+xl1J1SmzUMYz+0LubQxStFBKt8UUxuOBRdHrBRNQSTqXcjWtBII/zEuBTrhM1zo9lBaIb8/K6rUcsuhRqs1ONhzDalkFoA6KEo4oFtDeSTUAjF8lZG6Mrnp9nvPMV/4ovVSKdcijmd29rvXXgekwLua6DKjQN8dNd4/ykLHe2VNiHTVQ+6zRjHh2r5p92ujtC2i41Lk5d8DhQDxOyOzv0KxRA="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
