appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: baVmRRB7KIKcul77P9KNciQcobE8icrgSemCQCPaKG76M+UYNRCsbhpnxYVJaqjkGxWq3IAyFoKY+XK8woLthDN8cEoARDSyFGtyt4ijk2NmiWxOI8vNCR9xgtY3cpVjHwNvKH/b1CsqMNOUHygzmPtpRgZJSy1WKCXAIsNfG5+9MSuUyAp7zCsYrrBSHwm6/JpRl6H4h7n3xNZh7ohCsgdxpXYEISPmBXu0zd9tG/zD1AmolAVfUAdFvvMXckn0mbUzexJVESno0Orxv/KantICMaNkjaA8P2A9PdqsaspYTffgbTu2nOSnbGLoTZazR7a8Ab27/JYXgtV1sucBJjSsJ9+IfXLYi9DYiWobra/IKN5JOTX0peHmQhWQ8Xk5hOPnR9bjcm6XtoOlotSs2cI0LxGp0b4gwFiiQaU0mInrhvBQ9wq8j2F44fQI8Q7D+k92iJhwhNA/bTTj4ekYGHwS5EAWDDPsTl21BdsyQYMPIm3gBdIds/IazOeK5ngCRN1cUNwnK9jwi7uvLunmCCzUt8pvh2iEqWJr+hxDuSBnUBB37GoP8VY4hAaXaWc7KL0kANPw8zEVcXUuOACSZ1ARS5p4hb2jWXD6Aqty8mrVAlyKpsbwGlfv788xg2a0bHRjRfL4M4atHavOVpoOW+IfOI4Yl8aJ+8eRbxA1TnM=}
bot:
  automerge: true
